# This workflow will publish the package to PyPI when a new tag is pushed
# Make sure to set the following secrets in your GitHub repository:
#   - PYPI_USERNAME
#   - PYPI_PASSWORD (or PYPI_API_TOKEN for token-based auth)

name: pypi-publish

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write # Required for OIDC token
  contents: read # Required to checkout code

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI via Trusted Publisher (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
